function TripFooter() {
  return (
    <footer className="mt-16 mb-8 text-center">
      <div
        className="inline-flex items-center gap-2 px-6 py-3 rounded-full text-sm"
        style={{
          backgroundColor: 'var(--bg-subtle)',
          border: '1px solid var(--border)',
          color: 'var(--t3)',
        }}
      >
        🌍 Itinerary generated by AI Travel Planner
      </div>
    </footer>
  );
}

export default TripFooter;
